services:
  db:
    image: postgres:17
    container_name: db
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  api:
    build: .
    container_name: api
    command: bash -c "echo 'Starting migrations...' && python manage.py migrate && python manage.py collectstatic --noinput && echo 'Starting server...' && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
    driver: local
